apiVersion: v1
kind: Service
metadata:
  name: {{ include "stock-hpp.fullname" . }}-frontend
  labels:
    {{- include "stock-hpp.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "stock-hpp.selectorLabels" (dict "component" "frontend" "Chart" .Chart) | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: http
