---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-alertmanager-config
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    alertmanager.yaml: AgB3KjrF5E5h18vatG/peND62e1zooKM/T8gF/lOwKlaBdm6novhUuR7y3NHNPNtkIQ/9+cvTGmB38DZzz96rqln95v5S995gem8VfmKdEmJCxoS36zAAUayVOBNP/tPedlZ/HeGTO//uUlFiyw8BnqtkrDKyV7qJ71eqTpoQREkjN3oFp0RUpd+2vYVq//baRLfNXFgnPfmYyK188nh/7Ok0RWTDBWlrsv7qIG1APTWPCt1nEba+XtHlzxFx3T1YEEqSXPyIjljjHqBgJRReMWTI55i8ZHUx/6wRvnZG0rKTGQ6AJe7eM6J2eGWpJ8KSfavZElsFbJqUTRc3dQYurGYCRndC9wv7Xo2YgP3p+WS7rLmVNb4hvZTjuQL3X93ZpoRqlzoNuXp7dbsT7Djy9A9b+xYJ8Rst8FCB8ATJ3BIaRM0FrFydHtHHcrJ6c2Jt1aACTbM7lGFXLgHjdlJWdat92MvZM6oRjx90sgGif72aEug72h9eDtb62k5u4gBoImHVnKJnT5OI9/udZu857KgPtG6USR1sofEUEEd3ptP2i5sujOuzHhq3aJj52HO8NlFVUB6e+CHYBrJVZUxfae5P11GwOK2I9KZNTCc1EKEpQ8YA+wepPXjfvq4RIGonezOANfUUsoDg8KPFbgtabMyuLrDe9hTuqzW0Sa8OMPcFOV8DMxakR5SHaUq4iv0OacsF4PwttLBPldmOEJ3nDcWXNSNFTgZAyv71rQKX+jNNMsksgZIEjV139pAWgtrg7YuO2hTABGvDk8+/tMhqIo+HFwo78bOXge/H7976PFNYLqjUcYKoduPosptHZ4SHDLVbwP6YNjlmJS7DA1ZhNktlDyRYePPNx0wKsB4KfQmza4p5SS+jgPSzVXdxwYc2yYHwIZ7BAH4pqPntSKXfBAp36in8QTRArKZcpzSDAfoj4+l3EDX4twZwiz2t9qkTcxR5/0knqgzF1vTHVGleEXKwgrGaFj58ZF7YufHfu+z0O+mFNgKqxJT8YnICoeNTNskhte5xbtMIGmRqZVOdfn6rCDRE7IG15cCJFWWjsrMVv4pl+CEfyubpE62h4/mQVHgCe6jeRHZsUBSxVBrbAPf2u4V+0AiBal6NTvlwl7ztUstyGpawrOmjd45+MT76EoXYRqBIansYh3/63iYwhQtnQ==
  template:
    metadata:
      name: monitoring-alertmanager-config
      namespace: monitoring
