---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-alertmanager-config
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    alertmanager.yaml: AgDPOe1L4WWrvrZ0sCLN39/lG1npWm2LlckTrWXcFGVpqrUkJFRPr+0004YFsfPE2lGaC8kdsdgrdkbHi6zA6gI615zDfghpx6o5+Yn5KdQpImF9CF2ynGdrdFDeWJF3Q5yiaEBSnNx2OrSJfjKdJQtMZ/BvtYM4YL1Nd4ephr9QGtX/bfcXOQ+9TunSsLJpjsanVLCv5PCXJzfkfBdJ4z9FfmxVsORixFURl1n+ex/fatHxfU/g/JKwK8dEYV2yS/LkCafKPxxfvox0gaFbr5NU4Gg2+gWyYnNgGAXgNmxgKfcSFmzPHL4QH30YzFtnGlkM2enpAICMm3+ZYQvyu0uOhQ8i3I+b4WBxiapI1N7GL70jeWtYxvCA6PzvnTVcjVOTBD589dZ9plxpiq9h31BogoFJmOPZWSk21m6tqgQfzyJUtT0K6QMdQHgoP2g4kMehbARMRTV6Cw0P+hfv0MM2MjKEjUso8eqrSP6/Hev/AvuaPlQQByTNzYPfGHquHOXgM4PUNyfVDi43TF0OgesN0befVAEHqKGUzuhyzINirh0EFdWYsHZBsLOVCK9DvMbJruYe054a+yH6/h05W4Fxq4iqdLkcWDKrvM6ZsDmvh6/K9QADVW6BREB0wmw3WicVRkyZqS7JA03AYT9B7YEGpnQ2LAGro7pRR31vOo5fUf+dT8jSOkXnZj+BZBvtGrsMEgdr/MuK2eZNCuFBjqgUmRj2NxvXbuOX6SY3Q1y7dvieeQuMPii471KhAiqHtcazaP0kRkFtwKkpdwWF9BgVXd6tP7u2txfIxtFAAenGA4p0WXPwXfd/mno7r5yd2BbUitjp8kUSrgo4b6FB6SktubvnF5ODGtiITgBWIaMWKWko/N6qz1VUmvSwKTWoiCjO6UsOZHO8hCtLaDXgw2rBj983Sg/g6AM/nobEwAVjqaACyo9JkVnNgOSCxol6N7G1i7NSBFJHmTI88aHlhINByzqdPQnXqWv2c5gH6yTIobOX61q3fMVoG7j10dDPNvWYCIZsxGKwjF/hUma5QRcpPDZ7nWEgfsq9cLViTUY8hlFr7GuusqI/qdvdn+2L
  template:
    metadata:
      name: monitoring-alertmanager-config
      namespace: monitoring
