---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-alertmanager-config
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    alertmanager.yaml: AgAAQYbMTalxUM6mk8qXwHeenN1nvUUOqy1Xj/1DFmMmOtA+5Zr15uZpGRd75kEMtjWT0nuucKAvGR0F5HY2In87ilOwORtH4XMrQkZcEE0AmrguAsRPblxxqKPxlqDgjHXk6HcBK/fQyqFlB4Bso8D2AGEyj4y9TKb9FoaTboNubOu75CEPevuURh9ZVk2LOqgGiMuoykZ9u8MjXUBkjdtZqKITAH05sV3Asl9/Qd1ZzlIrVnyho1UM01jsAYhL3C4DIDjGcggfYMuYG2X0629I070pxZgng96r8Wv//hdQ6ILM/tgDhmJ9JV7UYbYACCPjSH8XjUcywOgLyN4JzeMWD+y/n6KPdOh9VzkUqdg1nbaO5JUFGau5VXFNgusB8O3fZnpiX4wPJ34WWDQ1D5XOIan9Q9As2S0H9G+34c78oOatj3+RJZJ/uxJs+eGKAQUiVDM6Ce8Ouy+G7/t5/OPJOkXl1BSG775B7X64umeYSghYy56rwhs4oYQSiTJekCFem/e7VAYlZXrIpmTLdF4lpN/5o5YORGBEJrdXytWcuHNuuF0gUAD7L9y5xO4EAXdh28UGYxoAuhuz6FfHKKs84mfyTDweuxCSm4joWUEeRpXpnMcYNSbMo2PvVCwPApzEKtHxgSLHuv+iojb7+jTsPtQaV6Qp18GtXh2VIVZdnnGF4rgsZe05JONwM62ZJAYgUT242rRc7KzBIuwqWWNOxJp90fYwfIMOUL+DWUZtbamrrE6Lk1fpwJvF8Ou3SD4+Gt1Nr2bYSyYYetmuD38klNBi8K/AsQDeBl9hhXE6jWFk2EbIdu4EWdmsCsMOwsv90WaPgyPyXcgeGwoFkAimSj7awNKuqjUH0ovLC4rrJVufQ9rpIDqh9jkm03b984hitcs10TKVCUWYOXm+plorLmGxvTrNsM/whxPivL/w3FN6cAJiGQ6sLc6tdfM8GDUa7PH6Xj/J3IffIDyAUAawGLfgdhHkBBCUQmZJwA2vPplGPBUs+fnY5brSqYVNHRg7cXDsLzyft5g8k1Yv9Q9K1cbiXFVg+IElb4xgToXaQAnnwTbCF/xc8ZjHmeTUxA27/7Fupm5ZkaWlyR5b8tAm9jIGrCMiO8oFXK2eWrxewWuTF0AEYXa4PN08g+Fdg+pvwvBcSfEYUy891J0Aa0dLTw==
  template:
    metadata:
      name: monitoring-alertmanager-config
      namespace: monitoring
