---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-grafana-admin
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    admin-password: AgC/Xa2N7+4PquV60pNKHztiK182pTlaoqMIheD1aRvbNqLeEVeBLvP0L2LbBb6r7OfmUj0XiDcPUyN0kFhXdhCPD2j3fL5idFc1WW3CtsmANGDxFzrp6HNAkI62en3ITOF96HC1p1R9vTriboFMVaPlwVbT/vLpuDwiwO089tLTManhZlPv3+XC3v+TJ2AOcFwFsbdHa5njK9g2c3DVUTo+HjTFZ11W+VUj1gpd0BmogHSoIg/yf7oT0TWfGzWuWNEvy2yVOMDMurmKBgS9CTsiX/4z+swwvrxURMI8sRXKqmTqmyYzE4Jyl0zqtUfHzJhxDi3c6XLM6GmWnyN2PcbnVkUsHjTU+q9c0s2Lj4MnAWC9ExZGmzXMZL0chNDnCWR0krP6q7XzxXWRsUKrizVylS2FCLU/lYSpnRiKIuehA+9w90+uZPimgmvvxj/aqpRVnwIc/Voh/ge5Z5YvDhYOH28QKqYo2JdPyLuzJhAsWBSw24rBZsnJ+e5lypn8pL/mzy5uToRfxIwMyO8FOg61gSz9XGwBGoRBRGxWpAC5QxNT3/NgyorOZ+zFiH5MwudLehwTNI+P5jwa5/97AsZu11NAP7b4FMGH5F+Lg1m3UFl3txXvIGp5sPWACYFrcgdRyIRaKeh7aHIY7egauVwt88LyICr3DOh6N+0V5aDgLrtOpeU42TY826P++Tvs3syjdxV43tjjAPSNPNCVnMU77Wx0mNWAAJnfgx4mJPWgJ+aMP3diZ3/CQNig1jO8DIs=
    admin-user: AgBa6HFF5uXVGN3b/3/71zVpgldJQmiSTu2zDhwGq71dJpA33SwvAI+17FCQ58Ls+k7l+kn7UUGoi1PBbF9RKlUFrzcv3DxMjt0kgkDDVkoZFNljDvo6nVPJ5Iq3BSh6P9sUUgge6xLrS8p37FtFBeIGSJpG9BMjWFjhjj3fMs5NPQ6wHPakj/2uXbH3GpGwCd3d5NrjLpjlYKhRKlaSb4vqizS/NSgo4HyINhMwDIf+Wy5h32eCafXYf23Q9NfKHC4m193pAoB8LMB9sQmVLyu9nX2Y2zmxXFjzOV5rs1NN1co7F24m3POoUwhS7slu2+KcDQkBdT3CqLuIg+ufWaoCOStwPW4rbh8YRRfnOC0LHhbhuyw00xGeWBani8XovV46ZNsGa761a21wHOtrFZYl1rUJNqjXu75qu736K7zjkMoVls5guNOGQjiW1tXCvQ905imYu920J9QTQS4fEQpyoGeQD/mszjR9P3DaK6xCTwjtSEWN5Ox+YxeLpgxUBrD7w211hLbtiYrZIvUGAvWnmmGq09zlMPLFcBsDmcewDRt9H7z+GpAGbUqaSJtwvBlhkt38pK6KfBCT1sGHc4hA8ii5AmSkclOAMpmPuazGlc5Gk0vzbIZymbIS9YszGo0lp75EErUwhvejrxeaSTgB+frxqs4hngBPUJhovU+FIXSFX08kjKkK6oJanDksHF+tL5CONQ==
  template:
    metadata:
      name: monitoring-grafana-admin
      namespace: monitoring
