---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-grafana-admin
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    admin-password: AgDBa7dvtTl/5EbP8pwRPPLWEcKB6Jg/LzAEy9ZJE7CjZhTauvkX6viDM/FRvkeyu2SrLDVL906ghD3Lw8U3w3524wQUSxgbHGZSpE3KESk6vSyVme7pi/f/NE2kiJAZFd7mlPprp2YW8wsRm1v376fmvpwSNv8BbKJWkZJpX/mtC2tO9dB9b8QVLoFcy1X1DnLNfNTrGtJWhxDqtbvQIHMO/JyAxyrud/q+X+B0d5iMz+dEihWLrV2+1y9GripCnC04jugVKLZ1vXCAbEtAyw6YBpGGdk/UlDU3vNeCsxh6aaotiSqq21v65knfz5CxVRfQyUEoiJLkVILgEG5i1DoHM5sbjUcHzVRMGxtaU8bRwTJVJfICsRSMmOIUTtYQiQYKvEe5L214nDaVI0sTNbynGr3QSg7z4K9lPbJ6Hdp7DUQkdzsjAqRtEiNnUTTNSWt4C2HKHTqL4mkKSlFJXiG5F0xT+ocTJp7HOWOCOyLGbR/aN09V20X23ZgiIHIXatlOvTe9HAcKCKeFPrt8zZCIAoTUalxzJcn7Y4BsVxDwngW6/+UI6W3MY/352DkWH5Mrxfp46mlcn9BZxuVH3Ii9JCLF9eewpF4Man48kdOElnz0IApELJYYqHvJc4XWyQYZeNL0uKHYLAVtHLkihFnik3pxtXgjeUlACCdMnc4XsjfUSubbyQWrtuF1SlBOxAfb0q60ZWY2tBVOtWbPxr3ScLonZ5WDKypmbVV8j6XPUgVBqjxNP7n3z9/U+sdGs0Y=
    admin-user: AgDAqWiz4nDjI2QBSKDRsCh+b6QRfarVr+HbdXHprOdOYF/MeWOxu7lB0vKJ6lhOw1roNuGlO1SMju04yB4mzaseB7HHEl297Yy9IfviJ81QlcCRLvs3xaqxKjHtbFy6kbEKdJ7fFfljjiO1yk0MjUZNj25WyuUCxp3peWWswKysAkAY+AqwwadAFUJCfBXxvbQ3DrSxKKYgaLXW7H0nZ9kq1n5Q12NsnNZFazfB6pB+yndrV296NKH+aFYljlzML7I+bVsylE6ezYNl2oIi/iayGeWFEqDzizDza0ZAvHUMOyr8AfBN4c/Zd8UVm8Yl4hqtpFzsKjiWmzXpZ8pNLFfYuk/UB0GaBV3H/wvLQByjOUC0WSvOubl5HMQksgqvOuvTYr3xiJnqU7yNbSanjEsApyTxvEkSOHyNnYGKDzDRHEJoN4gc80neG+ceH0u+/MQmioCY8d+l6EmxrH25a9iQozqvZOiWOCaCbHPGKm8n7OyQZPKfKzbH8IQFfC8DfpIIXFSh14cGGsoC7FCVLnAKruTX9rGpVLg/utZnoqurCnHlqzFBNZcQvQ3lB7v+O9J3U/MWnZ6pf7FHc1rh+MTa0g0qF0Bw0m3Ze/x9H1asjjjAd0v6GTDz/b9ThLa9U+bULZynJlSpWI+MBeDYjvQ0ItNrn90SbOHJA4aKv+XQWxrFijI/3TCfsRzTsOP54YH2495Kyw==
  template:
    metadata:
      name: monitoring-grafana-admin
      namespace: monitoring
