---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-grafana-admin
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    admin-password: AgA5/Y++mXrHlQeIPBJYxpOC9tC0ve5tejFGwQmlcwgKsDpbADTw+em7Hy5XQbivrjbvXkR4cHs6AFeEyM6VfGVk3H8a7exKWlt3Xndpng6A6f6iXlT8Nc/BBAyjIZr2iXV6etvu3RY6gMWRcPYkO8uEfM24XTSK/BOjGgHTDIb2WRqjey+sjj15ZwuNriMnkAWcjWDFWtkX2VPzGA0ZIWqcx7uVAE/clf9KsD9RQIY+2eG1A7BBkKTVPkehS4R2KcLmwCPsY/k5nVfoQfdKkKtpmcPuy7NfiiRwgZCrr+r+Iih3tphXkLkZJqZv9HQaeY65V7u4Axt9KKE60ciX0o0wYMbm4sZG/hEmL2IkYESbkramAOI3NYzeyT42RiwoHvES4rWL+6XyE8idEUaIAlXGuQczCqc96OhFOIg0SKmSwZvV1d7asFLlEbbkqGrv9HL4KdBVEQ1WKVhuH338HOgshuCaflvlg8hK/gw2cVYBifpTYdGuiSBx3Jdd5aluOn9JeNBsb85S1HWGZIoOyBw8dbge3hKOlhWvwQ4rZ1ac7RsKW01sevc69EEKoY0bWMZ+4SBNqlMkT5ZupaS69bnfn3zaPxxwpmh4SyiVYEyQ99KdVb2AcmWYx+WxlENbgpQE4zLJwbkB4PjUzT4RNCsr2x/p9UOOZY4Ie212XDXOuWeYnW37JfNJb4Es7u1QJRQL7IYJrg==
    admin-user: AgBfm6y3V2PpOlAuYT2L/ikliuj6quS4/ozbGBYSYyVy92LvmnlYUqQiXdSsj9+3BPgXsl6iCLbzW5FSwlk2BILbburuvVWl/3H9/zyro8o49wkwwXgKZsqK4via2Gp+NJmfKPAcdzu/fNXA00+osSxhfGbs8NqBzeU45nMRI1QGWfzy0odG0HqXXhMjf8VKesrRckrzbWCwJ/oWnkFxCyjAgWMh1PeJRMtsDXZPnHXWT9Fv2tcP7hpnuqUF57TNCU5zgkISL/pxi/jLCCdLHn0bazgO7Retk93iyntjvdnWRvMch06B0jELE/qB2y7w4eWF0dqRbsXwqEhu2JLT03hmmbQHBi5vZszsXwmtbFEJ7w7Z7Z8degVrzPPLzHqTMCt+42fiOxhU8g8tuTA10Q09Ae8a5VA7x81gI2t0asANOXCtxLkHkWt1kvcXXXX6NUTwBTGK8oGfSykpQ70YhC5wrfwrY0IuaNSjyfZL1G2AbvNCQHhJbhmdY5kiDdaSwV5tL+v3Rr7UTbmAjRTSfBXD6oqYdXnf1/pEZIfUhSywahqILKmM1ngSUYbPZY4Ht1yesc3YyxAQp/UnmeSnm519F+oVr/Phvp2ecx721py+jEQ5aFp2XHmtUcRpPZg/C1QpjsmXUwX0RTTtk0GdFzcXTnZSs8nu+hZJ5WZzWPhFDnE+bP4++aKDrOhYb2LghPny/6zDAA==
  template:
    metadata:
      name: monitoring-grafana-admin
      namespace: monitoring
